import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "../styles/globals.css";

import { cn } from "@/lib/utils";
import { Sidebar } from "@/components/sidebar";
import { playlists } from "@/data/playlists";

// const inter = Inter({ subsets: ['latin'] })

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <main className="grid grid-cols-5">
          <Sidebar playlists={playlists} className="hidden lg:block" />
          <section className="col-span-4">{children}</section>
        </main>
      </body>
    </html>
  );
}
